-- Migration: create article egg price detail table.
-- Scope: article analysis structured poultry-egg quote extraction.
-- Safety: CREATE TABLE IF NOT EXISTS is idempotent and does not touch group tables.

CREATE TABLE IF NOT EXISTS wechat_article_egg_price_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    article_hash VARCHAR(64) NOT NULL COMMENT '文章唯一hash，与article_analysis一致',
    account_name VARCHAR(200) NOT NULL COMMENT '公众号或订阅号名称',
    title VARCHAR(500) NOT NULL COMMENT '文章标题',
    publish_time DATETIME NULL COMMENT '文章发布时间',
    publish_date DATE NULL COMMENT '文章发布日期',
    item_index INT NOT NULL COMMENT '同一文章内报价明细序号',
    source_media_type VARCHAR(50) NOT NULL COMMENT '来源类型：dom_table/text_line/text_block',
    source_table_index INT NULL COMMENT 'DOM表格序号',
    source_row_index INT NULL COMMENT '来源行序号',
    source_table_title VARCHAR(300) NULL COMMENT '表格或段落标题',
    source_context_json TEXT NULL COMMENT '表格级或段落级上下文摘要，不保存全文',
    source_confidence DECIMAL(5,4) NULL COMMENT '规则解析置信度',
    product_family VARCHAR(50) NOT NULL COMMENT '产品族：chicken_egg/duck_egg/quail_egg/preserved_egg/salted_egg/other_egg',
    product_name VARCHAR(100) NULL COMMENT '原文产品名，如洋鸡蛋、红蛋、绿壳蛋、鸭蛋',
    include_in_egg_price TINYINT DEFAULT 0 COMMENT '是否纳入鸡蛋报价主口径',
    region VARCHAR(100) NULL COMMENT '地区',
    market_name VARCHAR(200) NULL COMMENT '市场、机构或报价主体',
    quote_basis VARCHAR(100) NULL COMMENT '报价基准，如30斤、27.5斤、360枚/箱',
    trade_scene VARCHAR(100) NULL COMMENT '交易场景，如到户、接货、装车、批发、收购',
    package_policy VARCHAR(100) NULL COMMENT '包装或运费规则，如含包装、不含包装',
    spec_text VARCHAR(200) NULL COMMENT '规格原文，如大码、45斤、52斤以上',
    weight_text VARCHAR(100) NULL COMMENT '重量原文',
    weight_low DECIMAL(10,3) NULL COMMENT '重量下限',
    weight_high DECIMAL(10,3) NULL COMMENT '重量上限',
    weight_unit VARCHAR(20) NULL COMMENT '重量单位',
    price_text VARCHAR(100) NULL COMMENT '价格原文',
    price_low DECIMAL(10,3) NULL COMMENT '价格下限',
    price_high DECIMAL(10,3) NULL COMMENT '价格上限',
    price_unit_text VARCHAR(50) NULL COMMENT '价格单位原文',
    yesterday_price_text VARCHAR(100) NULL COMMENT '昨日价原文',
    yesterday_price_low DECIMAL(10,3) NULL COMMENT '昨日价下限',
    yesterday_price_high DECIMAL(10,3) NULL COMMENT '昨日价上限',
    change_text VARCHAR(100) NULL COMMENT '涨跌原文',
    change_value DECIMAL(10,3) NULL COMMENT '涨跌数值',
    trend VARCHAR(20) DEFAULT 'unknown' COMMENT '趋势：up/down/flat/unknown',
    raw_headers_json TEXT NULL COMMENT '来源表头JSON',
    raw_row_json TEXT NULL COMMENT '来源行JSON',
    row_note VARCHAR(500) NULL COMMENT '行级备注，如以质论价、双色、32以下顺减',
    parse_notes_json TEXT NULL COMMENT '解析备注JSON',
    analysis_version VARCHAR(20) DEFAULT 'egg_price_v1' COMMENT '蛋价解析版本',
    analyze_time DATETIME NOT NULL COMMENT '分析时间',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_article_price_item (article_hash, item_index),
    KEY idx_article_price_account_date (account_name, publish_date),
    KEY idx_article_price_product_date (product_family, publish_date),
    KEY idx_article_price_region_date (region, publish_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
