from __future__ import annotations


SENSITIVE_BODY_FIELD_NAMES = (
    "msg_content",
    "raw_content",
    "clean_content",
    "markdown_body",
    "article_content",
    "article_body",
    "body_text",
    "html_content",
)

USER_FACING_DOC_PATHS = (
    "README.md",
    "docs/operations/微信群链路运行手册与验收清单.md",
    "docs/operations/公众号订阅号受控真实POC运行手册.md",
    "docs/operations/汇总日报运行手册.md",
    "docs/operations/小规模试运行方案.md",
    "docs/operations/日报质量人工评估表.md",
    "docs/operations/生产配置和回滚预案.md",
    "docs/operations/真实POC前置复核清单.md",
    "docs/operations/单公众号订阅号真实POC运行记录.md",
    "docs/operations/单核心群真实轮询POC运行记录.md",
    "docs/operations/双链路交错小窗口验证记录.md",
    "docs/operations/真实POC验收与扩容判断.md",
    "docs/operations/第九阶段真实POC执行准入冻结.md",
    "docs/operations/真实POC环境核验记录.md",
    "docs/operations/第九阶段单公众号订阅号真实POC执行记录.md",
    "docs/operations/第九阶段单核心群真实轮询POC执行记录.md",
    "docs/operations/第九阶段双链路交错真实小窗口验证记录.md",
    "docs/operations/第九阶段真实POC验收报告.md",
    "docs/operations/三公众号订阅号扩容配置记录.md",
    "docs/operations/三账号小规模交错POC运行记录.md",
    "docs/operations/三账号验收与二十账号扩容判断.md",
    "docs/design/公众号订阅号最多20账号扩容设计.md",
)

EXPORTED_GROUP_REPORT_GLOB = "runtime/reports/group/**/*.md"

SAFE_CLI_OUTPUT_KEYS_BY_COMMAND: dict[str, tuple[str, ...]] = {
    "check-config": (
        "env",
        "wechat_pc_version",
        "group_limit",
        "article_limit",
    ),
    "wechat-health": (
        "wechat_health_status",
        "message",
        "version",
    ),
    "group-config-list": (
        "group_name",
        "enabled",
        "is_core_group",
        "priority",
        "poll_interval_seconds",
    ),
    "group-config-upsert": (
        "group_config_upserted",
    ),
    "group-config-disable": (
        "group_config_disabled",
    ),
    "article-account-list": (
        "account_name",
        "account_type",
        "enabled",
        "priority",
        "poll_interval_minutes",
        "daily_window_start",
        "daily_window_end",
        "max_articles_per_round",
        "collect_today_only",
        "dedup_key",
        "last_success_collect_time",
    ),
    "article-account-upsert": (
        "article_account_upserted",
    ),
    "article-account-disable": (
        "article_account_disabled",
    ),
    "article-rpa-probe": (
        "article_rpa_probe",
        "status",
        "account_found",
        "link_count",
        "message",
        "rpa_error",
    ),
    "collect-article-once": (
        "account_name",
        "attempted_count",
        "success_count",
        "failed_count",
        "lock_timeout_count",
        "link_count",
        "raw_insert_count",
        "duplicate_count",
        "skipped_count",
        "task_created_count",
        "rpa_error",
    ),
    "run-article-scheduler": (
        "attempted_count",
        "success_count",
        "failed_count",
        "lock_timeout_count",
        "interrupted_count",
        "rpa_error",
    ),
    "parse-article-once": (
        "read_count",
        "success_count",
        "failed_count",
    ),
    "analyze-article-once": (
        "read_count",
        "success_count",
        "failed_count",
    ),
    "article-runtime-metrics": (
        "article_runtime_metrics",
        "window_hours",
        "account_total_count",
        "account_enabled_count",
        "collect_success_count",
        "collect_failed_count",
        "collect_skipped_count",
        "collect_total_count",
        "latest_error_summary",
        "article_task_backlog",
        "task_type",
        "status",
        "count",
        "article_metrics_error",
    ),
    "article-task-failed-list": (
        "failed_task",
        "id",
        "task_type",
        "ref_type",
        "ref_id",
        "status",
        "retry_count",
        "next_run_time",
        "error_summary",
        "update_time",
        "article_task_error",
    ),
    "article-task-retry-failed": (
        "task_type",
        "limit",
        "reset_count",
        "article_task_error",
    ),
    "article-daily-report-list": (
        "report_date",
        "account_name",
        "title",
        "article_count",
        "avg_content_length",
        "generate_time",
    ),
    "article-daily-report-export": (
        "export_path",
        "bytes_written",
        "article_daily_report_error",
    ),
    "summary-daily-report-export": (
        "export_path",
        "bytes_written",
        "summary_daily_report_error",
    ),
    "trial-monitor-report": (
        "trial_monitor_report",
        "hours",
        "group_success_count",
        "group_failed_count",
        "group_backlog_count",
        "article_success_count",
        "article_failed_count",
        "article_backlog_count",
        "ui_lock_timeout_count",
        "trial_monitor_report_error",
    ),
    "ai-analysis-sample": (
        "ai_analysis_sample",
        "source",
        "dry_run",
        "input_field_count",
        "provider",
        "prompt_version",
        "model_version",
        "model_called",
        "ai_analysis_error",
    ),
    "group-status": (
        "group_name",
        "enabled",
        "is_core_group",
        "priority",
        "poll_interval_seconds",
        "last_collect_batch_id",
        "last_success_collect_time",
        "consecutive_fail_count",
        "cursor_error_msg",
        "latest_log_status",
        "latest_log_read_count",
        "latest_log_insert_count",
        "latest_log_duplicate_count",
        "latest_log_error_code",
        "latest_log_screenshot_path",
        "ui_lock_owner_pipeline",
        "ui_lock_owner_task_id",
    ),
    "collect-group-once": (
        "group_name",
        "batch_id",
        "read_count",
        "insert_count",
        "duplicate_count",
        "rpa_error",
    ),
    "run-group-scheduler": (
        "attempted_count",
        "success_count",
        "failed_count",
        "lock_timeout_count",
        "rpa_error",
    ),
    "clean-group-once": (
        "read_count",
        "success_count",
        "failed_count",
    ),
    "analyze-group-once": (
        "read_count",
        "success_count",
        "failed_count",
    ),
    "group-daily-report-once": (
        "report_date",
        "generated_count",
    ),
    "group-daily-report-list": (
        "report_date",
        "group_name",
        "title",
        "message_count",
        "sender_count",
        "demand_count",
        "supply_count",
        "contact_count",
        "peak_hour",
        "generate_time",
    ),
    "group-daily-report-export": (
        "export_path",
        "bytes_written",
        "daily_report_error",
    ),
    "run-group-pipeline-once": (
        "pipeline_status",
        "failed_stage",
        "error_msg",
        "stage",
        "status",
        "read_count",
        "success_count",
        "failed_count",
        "generated_count",
        "batch_id",
        "group_name",
        "insert_count",
        "duplicate_count",
        "rpa_error",
    ),
    "group-runtime-summary": (
        "group_config",
        "total_count",
        "enabled_count",
        "core_enabled_count",
        "ui_lock",
        "status",
        "owner_pipeline",
        "owner_task_id",
        "expire_time",
        "task_backlog",
        "task_type",
        "count",
        "latest_collect",
        "source_name",
        "batch_id",
        "read_count",
        "insert_count",
        "duplicate_count",
        "error_code",
        "screenshot_path",
    ),
    "group-runtime-metrics": (
        "runtime_metrics",
        "window_hours",
        "collect_success_count",
        "collect_failed_count",
        "collect_total_count",
        "collect_failure_rate",
        "daily_report_count",
        "task_backlog",
        "task_type",
        "status",
        "count",
        "group_metrics_error",
    ),
    "group-task-list": (
        "task",
        "id",
        "task_type",
        "ref_type",
        "ref_id",
        "status",
        "retry_count",
        "next_run_time",
        "error_msg",
        "update_time",
    ),
    "group-task-reset": (
        "task_type",
        "ref_id",
        "reset_count",
        "group_task_error",
    ),
    "group-task-reset-date": (
        "task_type",
        "ref_id",
        "reset_count",
    ),
    "group-task-failed-list": (
        "failed_task",
        "id",
        "task_type",
        "ref_type",
        "ref_id",
        "status",
        "retry_count",
        "next_run_time",
        "error_summary",
        "update_time",
        "group_task_error",
    ),
    "group-task-retry-failed": (
        "task_type",
        "limit",
        "reset_count",
        "group_task_error",
    ),
}
